{
 "title": "Deployment",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment_namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation{job=\"kube-state-metrics\"},namespace)"
   },
   {
    "name": "deployment_name",
    "label": "Name",
    "query": "label_values(kube_deployment_metadata_generation{namespace=~\"^[[deployment_namespace]]$\"},deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^[[deployment_namespace]]$\",pod_name=~\"[[deployment_name]].*\",container_name!=\"POD\",container_name!=\"\"}[3m])) "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"^[[deployment_namespace]]$\",pod_name=~\"[[deployment_name]].*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"^[[deployment_namespace]]$\",pod_name=~\"[[deployment_name]].*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"^[[deployment_namespace]]$\",pod_name=~\"[[deployment_name]].*\"}[3m])) "
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=~\"^[[deployment_name]]$\",namespace=~\"^[[deployment_namespace]]$\"}) without (instance,pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=~\"^[[deployment_name]]$\",namespace=~\"^[[deployment_namespace]]$\"}) without (instance,pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{deployment=~\"^[[deployment_name]]$\",namespace=~\"^[[deployment_namespace]]$\"}) without (instance,pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{deployment=~\"^[[deployment_name]]$\",namespace=~\"^[[deployment_namespace]]$\"}) without (instance,pod)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=~\"^[[deployment_name]]$\",namespace=~\"^[[deployment_namespace]]$\"}) without (instance,pod)",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=~\"^[[deployment_name]]$\",namespace=~\"^[[deployment_namespace]]$\"}) without (instance,pod)",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=~\"^[[deployment_name]]$\",namespace=~\"^[[deployment_namespace]]$\"}) without (instance,pod)",
     "legendFormat": "unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=~\"^[[deployment_name]]$\",namespace=~\"^[[deployment_namespace]]$\"}) without (instance,pod)",
     "legendFormat": "updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=~\"^[[deployment_name]]$\",namespace=~\"^[[deployment_namespace]]$\"}) without (instance,pod)",
     "legendFormat": "desired"
    }
   ]
  }
 ]
}