{
 "title": "Kuberhealthy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kuberhealthy Running",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(kuberhealthy_running)" }
   ]
  },
  {
   "title": "Kuberhealthy History",
   "type": "graph",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(kuberhealthy_running)", "legendFormat": "Kuberhealthy Running" },
    {
     "expr": "avg(kuberhealthy_cluster_state)",
     "legendFormat": "Cluster State"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kuberhealthy_cluster_state)"
    }
   ]
  },
  {
   "title": "Kuberhealthy Check Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(kuberhealthy_check) by(check)"
    }
   ]
  },
  {
   "title": "Kuberhealthy Check History",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kuberhealthy_check) by(check)"
    }
   ]
  }
 ]
}