{
 "title": "Kubernetes Pods by Namespace and Node",
 "description": "Useful for noisy neighbor/node autoscaling concerns.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(machine_cpu_cores,instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace / Node memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^[[namespace]]$\",instance=~\"^[[Node]]:.*$\"}) / sum(machine_memory_bytes{instance=~\"^[[Node]]:.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Namespace/Node CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"^[[Node]]:.*$\",namespace=~\"^[[namespace]]\"}[1m]))/sum(machine_cpu_cores{instance=~\"^[[Node]]:.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Container/Node filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[nsx][v][bdm][a-z].+$\",instance=~\"^[[Node]]:.*$\",namespace=~\"^[[namespace]]$\",namespace!=\"\",container_name!=\"POD\"}) / sum(node_filesystem_size_bytes{instance=~\"^[[Node]]:.*$\",device=~\"^/dev/[nsx][v][bdm][a-z].+$\"}) * 100\n"
    }
   ]
  },
  {
   "title": "Namespace/Node Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name!=\"POD\",instance=~\"^[[Node]]:.*$\",namespace=~\"^[[namespace]]$\"})"
    }
   ]
  },
  {
   "title": "Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemFree_bytes{instance=~\"^[[Node]]:.*$\"})\n"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^[[namespace]]$\", container_name!=\"POD\", container_name!=\"\", instance=~\"^[[Node]]:.*$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\"^[[Node]]:.*$\"}) - sum(rate(container_cpu_system_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "Used (by containers)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[nsx][v][bdm][a-z].+$\",instance=~\"^[[Node]]:.*$\",namespace=~\"^[[namespace]]$\",namespace!=\"\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{device=~\"/dev/[nsx][v][bdm][a-z].+$\",instance=~\"^[[Node]]:.*$\"})\n"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase{phase=~\"^Running$\", namespace=~\"^[[namespace]]$\"} * on (pod) group_left (host_ip) kube_pod_info{host_ip=~\"^[[Node]]$\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase{phase=~\"^Pending$\", namespace=~\"^[[namespace]]$\"} * on (pod) group_left (host_ip) kube_pod_info{host_ip=~\"^[[Node]]$\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase{phase=~\"^Succeeded$\", namespace=~\"^[[namespace]]$\"} * on (pod) group_left (host_ip) kube_pod_info{host_ip=~\"^[[Node]]$\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase{phase=~\"^Failed$\", namespace=~\"^[[namespace]]$\"} * on (pod) group_left (host_ip) kube_pod_info{host_ip=~\"^[[Node]]$\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase{phase=~\"^Unknown$\", namespace=~\"^[[namespace]]$\"} * on (pod) group_left (host_ip) kube_pod_info{host_ip=~\"^[[Node]]$\"})"
    }
   ]
  },
  {
   "title": "Pods Total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=~\"^.+$\", namespace=~\"^[[namespace]]$\"} * on (pod) group_left (host_ip) kube_pod_info{host_ip=~\"^[[Node]]$\"})"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name,namespace)(rate(container_cpu_usage_seconds_total{namespace=~\"^[[namespace]]$\",instance=~\"^[[Node]]:.*$\",container_name=\"\"}[5m]))",
     "legendFormat": "{{ pod_name }}/{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{instance=~\"^[[Node]]:.*$\",namespace=~\"^[[namespace]]$\",container_name!=\"\",container_name!=\"POD\"}) by (pod_name,namespace)",
     "legendFormat": "{{ pod_name }}/{{ namespace }}"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^[[Node]]:.*$\",namespace=~\"^[[namespace]]$\"}[1m])) by (pod_name, namespace)",
     "legendFormat": "-> {{ pod_name }}/{{ namespace }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^[[Node]]:.*$\",namespace=~\"^[[namespace]]$\"}[1m])) by (pod_name, namespace)",
     "legendFormat": "<- {{ pod_name }}/{{ namespace }}"
    }
   ]
  }
 ]
}