apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  labels:
    k8s-app: grafana
spec:
  selector:
    matchLabels:
      k8s-app: grafana
  namespaceSelector:
    matchNames:
    - CUSTOM_NAMESPACE
  endpoints:
  - targetPort: 3000
    interval: 30s
    path: /metrics
  jobLabel: grafana-k8s
